In [42]:
import numpy as np

1) NUMPY ARRAYS

In [43]:
# using an array to reduce load time for lists containing multiple different parameters/characters
np.array([1, 2.71, True, "Hai-hai"]) ## It's gonna read it as a Boolean in Unicode

array(['1', '2.71', 'True', 'Hai-hai'], dtype='<U32')

In [44]:
# to read a whole number as a float
np.array ([1, 2, 3],  dtype="float")

array([1., 2., 3.])

In [45]:
# NumPy is great treating whit high dimension numbers // to see their dimension or shape
np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]).ndim # ().shape

3

In [46]:
# generating an array of a certain range
np.array(range(7))

array([0, 1, 2, 3, 4, 5, 6])

In [47]:
# zeros in a matrix / ones in a matrix
np.zeros((2,3)) # w/o integers, just whole numbers -> (()), dtype="int8")
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [48]:
# filling numbers in a certain range
np.arange(6)
np.arange(1,2, 0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [49]:
# linspace() for smthn same as above
np.linspace(1, 2, 11) # a range of 2 numbers splitted by 11 pivotal points

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ])

In [50]:
# zero matrix with a ones diagonal
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
# establishing a 
np.diag([3,4,5])

array([[3, 0, 0],
       [0, 4, 0],
       [0, 0, 5]])

2) GENERATING RANDOM NUMBERS

In [52]:
rng = np.random.default_rng() 

In [53]:
rng.random()

0.8335969238980021

In [54]:
# command uniform so we randomize a matrix
rng.uniform(low = 0 , high = 10, size = (3,3)) # provides samples from a uniform distribution
# we can use seeds too

array([[2.57280594, 7.34519041, 9.31702684],
       [0.81825279, 4.03333373, 0.3422087 ],
       [0.14979107, 0.47534427, 4.29148902]])

In [55]:
rng.normal(size = 20) # list of 20 parameters

array([-1.13888603, -1.51296568, -0.5581904 ,  2.21389685,  1.37201922,
       -1.82943811,  1.2394921 ,  0.28633882, -0.25111619,  0.76603889,
       -0.90164986,  1.38367356,  2.3385896 , -0.01787488, -0.17912859,
       -0.24653731,  0.58372014,  1.32208539, -0.25739308,  0.35209776])

In [56]:
rng.normal(20, 4, size = 4)

array([21.21276734, 20.16330512, 16.29787736, 26.36617498])

In [61]:
# SAMPLE NUMBERS OUT FROM A LIST
square = [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
rng.choice(square, size = 20)

array([36,  1, 49, 36,  4,  9,  0, 64, 49, 36,  9,  1,  9,  0, 16, 64,  0,
       16,  4, 36])

In [63]:
# ALSO CAN BE LIKE THIS
sqr = np.arange(10)**2
rng.choice(square, size = 20, replace = True)

array([ 0, 64, 16, 49, 81, 25, 81,  0, 49, 49,  4,  9, 16, 25,  0, 64,  1,
        0, 64,  9])

3) VECTORIZED OPERATIONS

In [64]:
x = np.arange(5)
y = np.array([-1, 0, 1, 0, -1])
A = rng.poisson(5, size=(3,3))
A

array([[8, 7, 4],
       [5, 5, 5],
       [5, 2, 6]], dtype=int64)