In [2]:
import numpy as np

In [3]:
# crear arreglo de 1D con 5 elementos
arr1 = np.array([1,2,3,4,5,6])

print("Arreglo 1a: ", arr1)
print("Forma(shape): ", arr1.shape) # N° dimensiones
print("Tipo de dato(dtype): ", arr1.dtype)

Arreglo 1a:  [1 2 3 4 5 6]
Forma(shape):  (6,)
Tipo de dato(dtype):  int32


In [4]:
# Cambiar la forma del arrgelo a una matriz 2x3

arr2 = arr1.reshape((2,3))
print("Arreglo 2a: ", arr2)
print("Forma(shape): ", arr2.shape)
print("Tipo de dato(dtype): ", arr2.dtype)

Arreglo 2a:  [[1 2 3]
 [4 5 6]]
Forma(shape):  (2, 3)
Tipo de dato(dtype):  int32


In [5]:
# Crear una matriz random con forma (4,4) y numeros aleatorios entre 0 y 1.
matrix = np.random.rand(4,4)
print("Arreglo 2a: ", matrix)
print("Forma(shape): ", matrix.shape)
print("Tipo de dato(dtype): ", matrix.dtype)

Arreglo 2a:  [[0.12162284 0.56507473 0.97474346 0.67360104]
 [0.3751715  0.40411871 0.04702015 0.3319824 ]
 [0.86913493 0.25231643 0.26258002 0.85155401]
 [0.17397052 0.14834279 0.7458101  0.85203141]]
Forma(shape):  (4, 4)
Tipo de dato(dtype):  float64


In [7]:
# Crear un arreglo de 2D a partir de una lista de listas

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr, type(arr))

[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>


In [11]:
# Crear un arreglo de ceros/unos con una forma (3,4)
arr = np.zeros((3,4)) # np.ones((3,4))

# point and change certains values
arr[1,2] = 10

print(arr)

[[ 0.  0.  0.  0.]
 [ 0.  0. 10.  0.]
 [ 0.  0.  0.  0.]]


In [12]:
# Crear una matriz identidad
arr = np.eye(4)
print(arr)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
# Create a 3D zero-matrix arrange with a (2,3,4) shape
arr = np.zeros((2,3,4)) # multidimentional
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [16]:
# randomize 2,5 matrix
arr = np.random.rand(2,5)
arr

array([[0.99653553, 0.33560516, 0.48978114, 0.59420892, 0.79796935],
       [0.25871413, 0.07786727, 0.78283865, 0.69561015, 0.00699666]])

In [17]:
# wanna transpose ?
arr.T

array([[0.99653553, 0.25871413],
       [0.33560516, 0.07786727],
       [0.48978114, 0.78283865],
       [0.59420892, 0.69561015],
       [0.79796935, 0.00699666]])

In [18]:
# for concatening

arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])
arr1, arr2

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [19]:
# concatening rows w/ r and columns w/ c, depending on the case (hztly or verticaly)
arr_h = np.hstack((arr1,arr2))
arr_h # HORIZONTALY Stacked

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [20]:
# VERTICALY Stacked
arr_v = np.vstack((arr1,arr2))
arr_v

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])