In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [3]:
# Calculate sum of elements
suma = np.sum(arr)
suma

15

In [4]:
# Promediate elements
promedio = np.mean(arr)
promedio

3.0

In [5]:
# Calculate median
median = np.median(arr)
median

3.0

In [6]:
# product of elements
product = np.prod(arr)
product

120

In [7]:
# Standar deviation
desv_est = np.std(arr)
desv_est

1.4142135623730951

In [8]:
# Varianza
var = np.var(arr)
var

2.0

In [9]:
# min element and max one
minim = np.min(arr)
maxim = np.max(arr)
minim, maxim

(1, 5)

In [10]:
# Cumulative sum
cumsum = np.cumsum(arr)
cumsum

array([ 1,  3,  6, 10, 15])

In [11]:
# sum element-wise
arr + arr # each indexed element is sum

array([ 2,  4,  6,  8, 10])

In [12]:
# substraction element-wise
arr - arr

array([0, 0, 0, 0, 0])

In [13]:
arr * arr

array([ 1,  4,  9, 16, 25])

In [14]:
arr / arr

array([1., 1., 1., 1., 1.])